# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# 1. GitHub
[[social]]
    name = "GitHub"
    weight = 2
    url = "https://github.com/J1ngZ112"
    [social.params]
        icon = "brand-github" # 这里的名字对应图标

# 2. 邮箱 (Email)
[[social]]
    name = "Email"
    weight = 1
    url = "mailto:jzfeng0112@gmail.com"
    [social.params]
        icon = "mail" 

# 3. 哔哩哔哩 (Bilibili)
[[social]]
    name = "Bilibili"
    weight = 3
    url = "https://space.bilibili.com/63945101"
    [social.params]
        icon = "brand-bilibili"

[[social]]
    name = "Instagram"
    weight = 4
    url = "https://www.instagram.com/jzfeng.112?igsh=MXZnNGhsZmpiMGxqNw%3D%3D&utm_source=qr" 
    [social.params]
        icon = "brand-instagram"

[[social]]
    name = "Tiktok"
    weight = 5
    url = "https://v.douyin.com/QZgqYzzBD6w/" 
    [social.params]
        icon = "brand-tiktok"

